apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubiya"
  description: "onnestop app for an organization"
  annotations:
    github.com/project-slug: ScaleupInfra/kubiya
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
